name: flutter_faem_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: 0.12.1
  scoped_model: ^1.0.1
  autocomplete_textfield_modified: ^1.6.11
  autocomplete_textfield: ^1.7.3
  sync_http: ^0.2.0
  phone_number: any
  device_id: ^0.2.0
  shared_preferences: any
  intl: ^0.16.1
  flutter_masked_text: ^0.8.0
  flutter_switch: ^0.1.0
  flutter_svg: any
  url_launcher: ^5.4.11
  flutter_typeahead: ^1.8.6
  flutter_sticky_header: ^0.4.2
  sticky_headers: ^0.1.8+1
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  firebase_messaging: ^7.0.0
  firebase_analytics: ^5.0.15
  flutter_launcher_icons: ^0.7.5
  flutter_local_notifications: ^1.4.4+5
  flutter_rating_bar: ^3.2.0+1
  flutter_staggered_grid_view: ^0.3.2
  webview_flutter: any
  centrifuge: ^0.5.1
  flutter_bloc: ^6.1.1
  amplitude_flutter: ^2.2.2
  video_player: ^1.0.1
  transparent_image: ^1.0.0
  carousel_slider: ^2.3.1
  bubble_bottom_bar: ^1.2.0
  flutter_spinkit: ^2.1.0
  loading_animations: ^2.1.0
  pin_input_text_field: ^3.3.0
  platform_device_id: ^0.1.3
  mask_text_input_formatter: ^1.2.1
  geolocator: ^6.1.13
  fluttertoast: ^7.1.6
  google_maps_flutter: ^1.0.10
  location: ^3.2.1
  geocoder: ^0.2.1
  flutter_map:
  mapbox_gl: ^0.9.0
  provider: ^4.3.2+3
  minimize_app: ^0.1.1
  move_to_background: ^1.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/svg_images/FaemLogo.svg
    - assets/svg_images/Start.svg
    - assets/svg_images/whiteFaemLogo.svg
    - assets/svg_images/faemPoint.svg
    - assets/svg_images/clientPoint.svg
    - assets/svg_images/location_arrow.svg
    - assets/svg_images/ellipse.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
